<a href="https://colab.research.google.com/github/ishantg3/IRIS-LR/blob/main/Make_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Logistic Regression for Multiclass Classification


In [ ]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
# Define Dataset
X, y=make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=42)

## Using Multinomial Regression  

In [ ]:
# Define the multinomial Logistic Regression model for Multiclass classification
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.20, random_state=42 )

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_pred_proba=model.predict_proba(X_test)
y_pred_proba = np.round(y_pred_proba, 2)

In [ ]:
y_pred_proba

array([[0.08, 0.65, 0.26],
       [0.44, 0.28, 0.28],
       [0.25, 0.39, 0.36],
       [0.  , 0.77, 0.22],
       [0.77, 0.04, 0.19],
       [0.98, 0.  , 0.02],
       [0.06, 0.53, 0.41],
       [0.36, 0.1 , 0.54],
       [0.15, 0.34, 0.51],
       [0.31, 0.16, 0.53],
       [0.46, 0.14, 0.4 ],
       [0.93, 0.  , 0.07],
       [0.57, 0.01, 0.42],
       [0.93, 0.  , 0.07],
       [0.76, 0.04, 0.2 ],
       [0.82, 0.01, 0.17],
       [0.35, 0.1 , 0.54],
       [0.06, 0.42, 0.52],
       [0.19, 0.22, 0.59],
       [0.  , 0.95, 0.05],
       [0.19, 0.17, 0.65],
       [0.08, 0.39, 0.53],
       [0.73, 0.04, 0.23],
       [0.55, 0.21, 0.23],
       [0.69, 0.06, 0.25],
       [0.82, 0.02, 0.16],
       [0.03, 0.66, 0.31],
       [0.19, 0.21, 0.6 ],
       [0.43, 0.1 , 0.47],
       [0.92, 0.  , 0.08],
       [0.18, 0.59, 0.23],
       [0.96, 0.01, 0.03],
       [0.03, 0.39, 0.58],
       [0.08, 0.35, 0.57],
       [0.05, 0.59, 0.35],
       [0.07, 0.63, 0.3 ],
       [0.73, 0.11, 0.17],
 

In [ ]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2,
       0, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1,
       2, 0, 0, 2, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 2, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 1, 1, 0,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print("confusion_matrix:", confusion_matrix(y_pred, y_test))
print("accuracy_score:", accuracy_score(y_pred, y_test))
print("classification_report:", classification_report(y_pred, y_test))

confusion_matrix: [[52  5 11]
 [ 8 47 17]
 [ 8 13 39]]
accuracy_score: 0.69
classification_report:               precision    recall  f1-score   support

           0       0.76      0.76      0.76        68
           1       0.72      0.65      0.69        72
           2       0.58      0.65      0.61        60

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.69       200
weighted avg       0.69      0.69      0.69       200



## Using One Vs Rest (OVR)

In [ ]:
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [ ]:
 y_pred=model.predict(X_test)

In [ ]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 2, 0, 1,
       2, 0, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 1, 0, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1, 2,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print("confusion_matrix:", confusion_matrix(y_pred, y_test))
print("accuracy_score:", accuracy_score(y_pred, y_test))
print("classification_report:", classification_report(y_pred, y_test))

confusion_matrix: [[54  6 14]
 [ 7 45 17]
 [ 7 14 36]]
accuracy_score: 0.675
classification_report:               precision    recall  f1-score   support

           0       0.79      0.73      0.76        74
           1       0.69      0.65      0.67        69
           2       0.54      0.63      0.58        57

    accuracy                           0.68       200
   macro avg       0.67      0.67      0.67       200
weighted avg       0.69      0.68      0.68       200

